# Generated by Django 5.2.3 on 2025-06-12 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название привычки')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Описание (необяз.)')),
                ('period', models.CharField(verbose_name='Периодичность (daily/weekly)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна/неактивна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнено (да/нет)')),
                ('comment', models.CharField(blank=True, null=True, verbose_name='Комментарий (необяз.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date'],
            },
        ),
    ]
