# Generated by Django 5.2.3 on 2025-06-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Еженедельная'), ('monthly', 'Ежемесячная'), ('yearly', 'Ежегодная')], verbose_name='Периодичность (daily/weekly)'),
        ),
    ]
